<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>ab948bd5-1007-4d6c-802f-e13a761b9a54</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined 
then
	set decision to `Hello {'Name'}! {'Weather Advice'}` ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
